### ISSUE TITLE
Selected Value (Icon) does not accepted into Input Fields

### ISSUE THREAD

**Issue by 47gn** [codefog/contao-iconpicker#1]
Hi Kamil,

can you help me please with the following problem:

I can select the Icon and i see the name and den image from the selected icon in the input field. Now ic click Submit, there is always save the value "icon-phone".

If i debugg, there is no JS Error to see. 

I use Contao 3.5.19 and your masterbrunch from the icon picker.

Thank you very much :)

**Comment by qzminski** [comment]
Hey Holger, this extension has no stable version so please use the develop branch.

**Comment by 47gn** [comment]
Hi Kamil, thanx a lot - it works :)
